### ISSUE TITLE
Provide an option to append to an existing spreadsheet

### ISSUE THREAD

**Issue by past** [past/tsci#18]
Appending to a specified master spreadsheet will be a more streamlined process so let's do that.

**Comment by miketaylr** [comment]
A few relevant docs:

https://developers.google.com/sheets/api/samples/sheet
https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/request#addsheetrequest

**Comment by past** [comment]
In my master spreadsheet I added a summary sheet and a chart. I suspect we will implement their updates in this issue.
