### ISSUE TITLE
Determine the right list size to use

### ISSUE THREAD

**Issue by past** [past/tsci#24]
Arguably, the larger the site list, the more accurate the metric. I wonder what that means in practice for our purposes though, since larger list sizes result in a slower to compute index. I would like to compare the TSCI results when using various list sizes as input, for the same date.

I posit that we don't care about a list larger than 500 if the TSCI doesn't change by at least 1 or 1%, whichever is bigger. This is a bit handwavy, but that's the best I can come up without actual data. Our current numbers are in the low hundreds.

**Comment by past** [comment]
So as expected, the weighted TSCI doesn't change much with 500, 1K or 5K sites:
500: 238.5
1K: 238.7
5K: 239.7

The non-weighted TSCI however changes much more:
500: 1751.8
1K: 1914
5K: 3378.5

Execution time also changes dramatically:
500: 30 min
1K: 56 min
5K: 355 min (~6 hrs)

**Comment by past** [comment]
@adamopenweb this is something I'd like us to make a decision on next week. Using the weighted TSCI seems like a no-brainer for what to target first, since it will let us focus on the biggest wins, but I think that monitoring how the non-weighted score is impacted by our ongoing work will be important, too.

**Comment by adamopenweb** [comment]
Thanks @past for validating. I agree with using weighted TSCI. And +1 for 500 sites, I think this is an optimal number and we can always validate later if the % difference has changed between 500 and 5k.

**Comment by miketaylr** [comment]
Agreed, let's go with 500. Thanks for doing the legwork here @past.

**Comment by past** [comment]
OK, 500 it is for now then.
