### ISSUE TITLE
Output of tsci is inconsistent with webcompat-bugcount-report-generator

### ISSUE THREAD

**Issue by miketaylr** [past/tsci#3]
I'll do this.

**Comment by miketaylr** [comment]
The sites won't line up exactly, so I think I'll just verify the top 25 from the "Mozilla" list to the output of the Tranco ones.

**Comment by miketaylr** [comment]
Since I ran into #4, I restricted this to 5 sites.

It looks like the Bugzilla counts are correct, but the webcompat.com ones are not (see node-scraper vs python scraper tabs):

https://docs.google.com/spreadsheets/d/1BRPvEznhqbwLYARQdV0xOI4h98EY4iRojkHKg3bNHv0/edit#gid=2074253124

**Comment by miketaylr** [comment]
Duplicates are also incorrect. Basically only Bugzilla is correct right now.

**Comment by miketaylr** [comment]
I think for `getWebcompat`, instead of the Issues octokit endpoints, we want to use search. IIUIC, the current approach is just getting the first (or last?) 100 issues (or whatever the default page 1 result is) from the repo and filtering based on the title. 

https://octokit.github.io/rest.js/#octokit-routes-search

**Comment by past** [comment]
@wisniewskit is this issue fixed after your latest changes? Could you do another comparison like [this](https://github.com/past/tsci/issues/3#issuecomment-494971545)?

**Comment by wisniewskit** [comment]
It seems to me that once #20 lands, the numbers should finally match up.

**Comment by past** [comment]
@miketaylr since you filed this, can you confirm that the two approaches now produce the same results?

**Comment by past** [comment]
(not today of course, I just wanted to document next steps)

**Comment by miketaylr** [comment]
Yep! Will do a fresh run tomorrow.

**Comment by miketaylr** [comment]
OK, just ran a crawl using tsci and the old python code, and did a spot check for 10 top sites. I think we have crawl-compatibility now.
