### ISSUE TITLE
Handle maxDate before 2018-12-01 (recover from tranco 503 response)

### ISSUE THREAD

**Issue by miketaylr** [past/tsci#31]
If you try to set `maxDate` to a date before `2018-12-01`, the tranco service will return a 503 (because the data doesn't exist). And then we throw an Error.

![Screen Shot 2019-05-31 at 4 21 20 PM](https://user-images.githubusercontent.com/67283/58735480-26d58e00-83c0-11e9-9a9b-3805b7c4566a.png)

**Comment by miketaylr** [comment]
@past should we just `process.exit(1);` here? Or just treat anything earlier than 2018-12-01 as 2018-12-01 and document as a limitation of the historical data?

**Comment by past** [comment]
I think using the earliest data we have for the more distant past would be our best option here. We should also generalize that rule to other dates that return an empty list. In pseudocode: 
`while(!fetchList(date++))`
