### ISSUE TITLE
Split out Desktop + Mobile bugs

### ISSUE THREAD

**Issue by miketaylr** [past/tsci#38]
We could treat desktop bugs as a range of columns, and the same for mobile, then graph them separately or as a composite thing.

I guess this will effectively 2x our report generation time.

**Comment by past** [comment]
How can we tell which bugs are desktop-only or mobile-only in bugzilla and webcompat.com?

**Comment by miketaylr** [comment]
> How can we tell which bugs are desktop-only or mobile-only in bugzilla and webcompat.com?

webcompat.com is easy -- we have labels we can filter on (`browser-firefox-mobile`, `browser-fenix`, etc). 
For Bugzilla, we have two options: 
    1. only include the bugs from the Fenix, Firefox for Android and GeckoView components
    2. include all the bugs from Core, as well as the bugs from the option above

@andreasbovens, thoughts?

I propose we only add an extra column for mobile-specific bugs and graph that line, and we can (sort of infer?) desktop from that.

**Comment by miketaylr** [comment]
^^ also ping @adamopenweb

**Comment by miketaylr** [comment]
>  2. include all the bugs from Core, as well as the bugs from the option above

Andreas voted for this option.
