### ISSUE TITLE
UnhandledPromiseRejectionWarning during getDuplicates

### ISSUE THREAD

**Issue by miketaylr** [past/tsci#4]
```
(node:5158) UnhandledPromiseRejectionWarning: Error: Bugzilla query failed!
    at fetch.then.res (/Users/miket/dev/tsci/bugs.js:236:27)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

https://github.com/past/tsci/blob/2ae0ab6316e1dac0cabb591dca1fe1e0389c82f2/bugs.js#L224-L236

(I think that should say GitHub query failed)

**Comment by wisniewskit** [comment]
From what I can tell, we just need to convert to using `octokit.request` instead of `fetch` in the above code so that it rate-limits (which is the source of the unhandled rejection in my testing).
