### ISSUE TITLE
Consider checking-in tranco lists

### ISSUE THREAD

**Issue by miketaylr** [past/tsci#50]
If we already have a cached list (which had `ignoredDomains` removed), it seems OK to check it into the repo and save ourselves a few HTTP requests. The perf hit probably is insignificant in the grand scheme of things, but it's interesting to consider having a stable historical archive in case Tranco goes down one day (or disappears entirely).

Things to consider: can we automate adding the new lists to the repo? 💀  Or should that be a manual process?

**Comment by past** [comment]
They have some attribution requirements for referencing the work, which makes it unclear what the terms of use are for caching it. We should contact them to find out if we want to pursue this.

**Comment by miketaylr** [comment]
Ah, excellent. Thanks for flagging that. Assuming they're OK with us doing so (maybe either in the README, or per commit-message), WDYT? Worth it? Not worth it? I'm not sure I have a strong opinion on this yet.

**Comment by past** [comment]
Shaving off some milliseconds it takes to fetch the script in a >1 hour run, isn't worth it. The preservation of historical data in case tranco goes under is somewhat interesting, but recreating past data from scratch even with a single list will still be possible (cached Tranco or from elsewhere), and the past data is only useful as a starting point (doesn't really impact future prioritization).

Therefore my fully considered and strongly held position is: ¯\_(ツ)_/¯

**Comment by miketaylr** [comment]
> Therefore my fully considered and strongly held position is: ¯_(ツ)_/¯

haha, fair. let's focus on more important problems.
