### ISSUE TITLE
Are we capturing the right GitHub bugs?

### ISSUE THREAD

**Issue by miketaylr** [past/tsci#56]
I had this suspicion before, but perhaps I was looking in the wrong place and didn't end up filing a bug.

If we look at the 5/5 sheet, which had the dramatic 50 point drop for Google: https://docs.google.com/spreadsheets/d/1rmH1EhTVZBtTIXXwqSHcaQXhmv7xJh2Y2LuNiySPURQ/edit?ts=5cf460c1#gid=1001621121

Clicking on the GitHub link: https://github.com/webcompat/web-bugs/issues?q=google%20com+created:*..2019-05-05+-closed:%3C=2019-05-05+in%3Atitle++label:engine-gecko+-milestone:needstriage

A *lot* of the closed ones are incomplete, invalid, non-compat, worksforme, etc. I don't think we want this -- we should only be capturing valid, triaged issues.

I suspect this is an artifact of how GitHub search works. We might have to do 4 searches for needsdiagnosis, sitewait, needscontact and contactready milestones and add them up. And maybe this will finally convince us to collapse needscontact and contactready (because I'm not convinced that's a useful distinction... but that's another story).

Thoughts @past @wisniewskit?

Unfortunately we can't just pile on `milestone:needsdiagnosis milestone:sitewait...` etc. I wonder if nemo's kibana thing can handle the more complex query? It apparently has an API...

**Comment by wisniewskit** [comment]
Using four queries shouldn't be too tough to code for a quick fix (as long as the total time to fetch everything doesn't get too ridiculous).

**Comment by miketaylr** [comment]
> Another option might be to just skip the ones we're not interested in after querying for all of them, if it's otherwise working fine.

This seems more appealing than 4 queries... let me play around with the responses and see how annoying it is to filter out stuff we don't want.

**Comment by past** [comment]
If you can't figure out how to fix the links, just defaulting to the sitewait milestone in the link would be OK, since it appears to be the biggest bucket. It's unfortunate that github's API works like this, but using the milestone drop down in the results page is not that hard.

**Comment by past** [comment]
And we have the same link problem in the bugzilla queries anyway, where we can't just add multiple links (in the bugzilla case, 4 in the github case) to a single cell.

**Comment by miketaylr** [comment]
> If you can't figure out how to fix the links, just defaulting to the sitewait milestone in the link would be OK, since it appears to be the biggest bucket. It's unfortunate that github's API works like this, but using the milestone drop down in the results page is not that hard.

I like this idea. My original idea in https://github.com/past/tsci/commit/6019c15eab86faa9890a67dc8dd1f78d9192e321 won't work because GitHub search queries are limited to 256 chars, so a result with 50 bugs just returns nothing:

https://github.com/webcompat/web-bugs/issues?q=23867%2019037%2017870%2019363%2013574%2029937%2018993%2018690%2017911%2016051%2016329%2014247%203067%203822%208900%203954%201676%202323%204776%204683%205938%205331%2019384%2029167%2028614%2027176%2017192%2018637%2016856%203616%206801%2013250%209975%2030456%202983%2029462%2026118%2023719%2022494%2019122%2017255%2016534%2010623%2010113%207350%207309%208753%208733%208645%2025880

**Comment by miketaylr** [comment]
I'll toss something together for the sitewait milestone after I get kids to bed.

**Comment by miketaylr** [comment]
> If you can't figure out how to fix the links, just defaulting to the sitewait milestone in the link would be OK, since it appears to be the biggest bucket.

I decided to just keep the links as-is. We can still easily select the milestones we're interested in, but these links will show all the bugs (except "needstriage") for a given week, open and closed. It's maybe interesting to get a glance at duplicate/invalid bugs too.
